update -> merge: Return and use the new merged collection in updateCollection()
Results in the following fail which makes sense:
org.osaf.cosmo.model.ModelValidationException: cannot add modification 1:20070101 to collection b, only master